# Generated by Django 4.1.6 on 2023-02-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('min_score', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
            ],
        ),
    ]
